name: Deploy pages
on: push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install packages
        run: bun install
      - name: Install slidev
        run: bun i -g @slidev/cli
      - name: Install for PDF
        run: bun i -D playwright-chromium
      - name: Build
        run: slidev build --base /slidev-tutorial/ # Change this line
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
